Submitting form with payload: {
  "transaction_type": 1,
  "cash_ref": 1,
  "payment_type": 1,
  "invoice_date": "2025-02-02",
  "invoice_no": "123",
  "supplier": 1,
  "currency": 1,
  "currency_rate": 1,
  "payment_term": 1,
  "total_amount": 1,
  "paid_amount": 1,
  "supplier_vat": 10,
  "created_by": 1,
  "items": [
    {
      "pr_item": 10,
      "po_item": null,
      "remark": "Ut omnis voluptatum ut et consequatur.",
      "qty": 83,
      "uom": "odit",
      "unit_price": 95.45,
      "discount": 0,
      "vat": 792.23,
      "return": 0,
      "retention": 0,
      "due_amount": 8714.59,
      "paid_amount": 0,
      "campus": "enim",
      "division": "minus",
      "department": "architecto",
      "purpose": "Numquam enim eligendi est inventore.",
      "location": "dd",
      "description": "Id quasi est voluptatem qui vero. | Ut omnis voluptatum ut et consequatur.",
      "pr_number": 15,
      "po_number": "",
      "item_code": "quis",
      "requested_by": 1,
      "cash_ref": 1,
      "transaction_type": 1,
      "payment_term": 1,
      "purchased_by": 1,
      "currency_rate": 1,
      "currency": 1,
      "invoice_date": "2025-02-02",
      "payment_type": 1,
      "invoice_no": "123",
      "id": null,
      "index": 0,
      "grand_total": 8714.58,
      "pi_number": null,
      "total_usd": 7922.35,
      "total_khr": 7922.35
    }
  ]
}